server:
  ip: localhost
  port: 9090
# 配置日志文件
logging:
  #config: classpath:logback.xml
  config: classpath:logback-spring.xml


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userloss_db?serverTimezone=GMT%2b8
    username: root
    password: 369369
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  #头像地址
  upload:
    path: D:\video\files\

  #上传的
  trainFile:
    path:  D:\video\data\train\

  predictFile:
    path:  D:\video\data\predictfile\

    #python 解释器
  pythonInterpreter:
    path: D:\anaconda3\python.exe

    # 模型代码训练所在的位置
  pythonTrianCode:
    path:  C:\Users\16084\Desktop\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统-代码与数据\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统-源代码\userlost\userLostTrain.py

  #模型代码预测代码所在问题
  pythonPredictCode:
    path:  C:\Users\16084\Desktop\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统-代码与数据\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统-源代码\userlost\userLostPredict.py

  # 模型代码训练与评估所在的位置
  pythonAnalyzeCode:
    path: C:\Users\16084\Desktop\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统-代码与数据\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统-源代码\userlost\userLostTrain_model_analysis.py

  # 模型代码训练所在的位置
  pythonEDAAnalyzeCode:
    path: C:\Users\16084\Desktop\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统-代码与数据\AIC-2025-99381413-AC4.6-AI多模型协同酒店用户流失预警系统-源代码\userlost\userLostEDA.py


